version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '2501:80'
        volumes:
            - .:/project
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    php:
        build: config/docker/php
        volumes:
            - .:/project

    pgsql:
        image: postgres:14
        ports:
            - '2502:5432'
        environment:
            POSTGRES_USER: links-johnnoel-uk
            POSTGRES_PASSWORD: links-johnnoel-uk
